name: Scheduled Workflow Example

on:
  schedule:
    # Runs at 3:30 AM UTC every day
    - cron: '*/5 * * * *'

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: |
          echo "This workflow was triggered by a schedule event!"
          date
